const ADD_TRASH_COORDINATE = 'ADD_TRASH_COORDINATE';
const RECEIVE_TRASH_COORDINATES = 'RECEIVE_TRASH_COORDINATES';
const FETCHING_TRASH_COORDINATES = 'FETCHING_TRASH_COORDINATES';
const STOP_FETCHING_TRASH_COORDINATES = 'STOP_FETCHING_TRASH_COORDINATES';

export default {
  ADD_TRASH_COORDINATE,
  RECEIVE_TRASH_COORDINATES,
  FETCHING_TRASH_COORDINATES,
  STOP_FETCHING_TRASH_COORDINATES,
};
