const RECEIVE_GARBAGE_BINS = 'RECEIVE_GARBAGE_BINS';
const FETCHING_GARBAGE_BINS = 'FETCHING_GARBAGE_BINS';
const STOP_FETCHING_GARBAGE_BINS = 'STOP_FETCHING_GARBAGE_BINS';

export default {
  RECEIVE_GARBAGE_BINS,
  FETCHING_GARBAGE_BINS,
  STOP_FETCHING_GARBAGE_BINS,
};
